import DefaultNavbar from "@/components/level_one_layout/default_navbar";
import DefaultSidebar from "@/components/level_one_layout/default_sidebar"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (<>
  <DefaultNavbar/>
  <DefaultSidebar/>
  {children}
  </>
  );
}
