import DefaultFooter from "@/components/level_one_layout/default_footer";
import DefaultNavbar from "@/components/level_one_layout/default_navbar";
import DefaultSidebar from "@/components/level_one_layout/default_sidebar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex h-screen">
      <DefaultSidebar />

      <div className="flex flex-col flex-grow">
        <DefaultNavbar />

        <main className="flex-grow p-4">{children}</main>

        <DefaultFooter />
      </div>
    </div>
  );
}





// import DefaultFooter from "@/components/level_one_layout/default_footer";
// import DefaultNavbar from "@/components/level_one_layout/default_navbar";
// import DefaultSidebar from "@/components/level_one_layout/default_sidebar"

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (<>
//   <DefaultNavbar/>
//   <DefaultSidebar/>
//   <DefaultFooter/>
//   {children}
//   </>
//   );
// }
